using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CvMatchingSystem.Data;
using CvMatchingSystem.Models;
using Microsoft.AspNetCore.Authorization; 
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace CvMatchingSystem.Controllers
{
    [Authorize]
    public class ResultsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ResultsController(ApplicationDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.MatchingResults
                .Include(m => m.Candidate)
                .Include(m => m.JobPosting)
                .OrderByDescending(m => m.CreatedDate);
            return View(await applicationDbContext.ToListAsync());
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null) return NotFound();

            var matchingResult = await _context.MatchingResults
                .Include(m => m.Candidate)
                .Include(m => m.JobPosting)
                .FirstOrDefaultAsync(m => m.Id == id);
            
            if (matchingResult == null) return NotFound();

            return View(matchingResult);
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null) return NotFound();

            var matchingResult = await _context.MatchingResults
                .Include(m => m.Candidate)
                .Include(m => m.JobPosting)
                .FirstOrDefaultAsync(m => m.Id == id);
            
            if (matchingResult == null) return NotFound();

            return View(matchingResult);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var matchingResult = await _context.MatchingResults.FindAsync(id);
            if (matchingResult != null)
            {
                _context.MatchingResults.Remove(matchingResult);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> ExportToPdf(int id)
        {
            QuestPDF.Settings.License = LicenseType.Community;

            var matchingResult = await _context.MatchingResults
                .Include(m => m.Candidate)
                .Include(m => m.JobPosting)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (matchingResult == null) return NotFound();

            string candidateName = matchingResult.Candidate?.FullName ?? "Unknown";
            string jobTitle = matchingResult.JobPosting?.Title ?? "Unknown";

            var document = Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Size(PageSizes.A4);
                    page.Margin(2, Unit.Centimetre);
                    page.PageColor(Colors.White);
                    page.DefaultTextStyle(x => x.FontSize(11).FontColor("#1a1714"));

                    page.Header().Row(row =>
                    {
                        row.RelativeItem().Column(col =>
                        {
                            col.Item().Text("AI MATCHING REPORT").SemiBold().FontSize(20).FontColor("#c17b3c");
                            col.Item().Text($"{DateTime.Now:MMMM dd, yyyy}").FontSize(10).FontColor(Colors.Grey.Medium);
                        });
                    });

                    page.Content().PaddingVertical(1, Unit.Centimetre).Column(x =>
                    {
                        x.Spacing(15);
                        x.Item().Row(row => {
                            row.RelativeItem().Text("Candidate:").SemiBold();
                            row.RelativeItem().Text(candidateName);
                        });
                        x.Item().Row(row => {
                            row.RelativeItem().Text("Target Position:").SemiBold();
                            row.RelativeItem().Text(jobTitle);
                        });
                        x.Item().PaddingVertical(5).LineHorizontal(1).LineColor("#e2ddd6");
                        x.Item().Row(row => {
                            row.RelativeItem().Text("Compatibility Score:").FontSize(14).SemiBold();
                            row.RelativeItem().Text($"{matchingResult.Score}%").FontSize(18).Bold().FontColor("#c17b3c");
                        });
                    });

                    page.Footer().AlignCenter().Text(x =>
                    {
                        x.Span("Generated by Nexus AI Matching System").FontSize(9).FontColor(Colors.Grey.Medium);
                    });
                });
            });

            byte[] pdfBytes = document.GeneratePdf();
            return File(pdfBytes, "application/pdf", $"Report_{candidateName.Replace(" ", "_")}.pdf");
        }
    }
}