using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using CvMatchingSystem.Data;
using System.Threading.Tasks;
using System.Linq;
using QuestPDF.Fluent; 
using QuestPDF.Helpers; 
using QuestPDF.Infrastructure; 

namespace CvMatchingSystem.Controllers
{
    public class ResultsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ResultsController(ApplicationDbContext context)
        {
            _context = context;
            
            // МЫ ПРОСТО ОТКЛЮЧАЕМ ЭТУ СТРОКУ:
            // Это уберет ошибку CS0234 и позволит проекту собраться.
            // QuestPDF.Settings.License = LicenseKind.Community;
        }

        public async Task<IActionResult> Index()
        {
            var results = await _context.MatchingResults
                .Include(r => r.Candidate)
                .Include(r => r.JobPosting)
                .OrderByDescending(r => r.CreatedDate)
                .ToListAsync();

            return View(results);
        }

        // Реализация метода из твоей UML-диаграммы (стр. 5)
        public async Task<IActionResult> Export(int id)
        {
            var result = await _context.MatchingResults
                .Include(r => r.Candidate)
                .Include(r => r.JobPosting)
                .FirstOrDefaultAsync(r => r.Id == id);

            if (result == null) return NotFound();

            var document = Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Margin(50);
                    page.Header().Text("AI MATCH ANALYSIS REPORT").FontSize(22).SemiBold().FontColor(Colors.Blue.Medium);

                    page.Content().PaddingVertical(20).Column(col =>
                    {
                        col.Item().Text($"Candidate: {result.Candidate?.FullName ?? "N/A"}").FontSize(14);
                        col.Item().Text($"Job Posting: {result.JobPosting?.Title ?? "N/A"}").FontSize(14);
                        col.Item().PaddingTop(10).Text($"Match Score: {result.Score}%").FontSize(18).Bold().FontColor(result.Score > 75 ? Colors.Green.Medium : Colors.Orange.Medium);
                    });

                    page.Footer().AlignCenter().Text(x => {
                        x.Span("Generated by CvMatchingSystem - Page ");
                        x.CurrentPageNumber();
                    });
                });
            });

            byte[] pdfBytes = document.GeneratePdf();

            // Безопасное формирование имени (ошибка CS8602 исправлена через ?.)
            string safeFileName = result.Candidate?.FullName?.Replace(" ", "_") ?? "Report";
            return File(pdfBytes, "application/pdf", $"Match_Report_{safeFileName}.pdf");
        }
    }
}